//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.5472
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnityScriptEditorRedirector.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnityScriptEditorRedirector.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Delete Redirector Config に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DeleteConfirm_Caption {
            get {
                return ResourceManager.GetString("DeleteConfirm_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete Redirector Config from Windows Registry! Are you sure? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DeleteConfirm_Message {
            get {
                return ResourceManager.GetString("DeleteConfirm_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Redirector Config Deleted に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Deleted_Caption {
            get {
                return ResourceManager.GetString("Deleted_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Complete to delete Redirector Config on your computer. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Deleted_Message {
            get {
                return ResourceManager.GetString("Deleted_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExecuteMySelf_Caption {
            get {
                return ResourceManager.GetString("ExecuteMySelf_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot execute myself! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExecuteMySelf_Message {
            get {
                return ResourceManager.GetString("ExecuteMySelf_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save Redirector Config に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveConfirm_Caption {
            get {
                return ResourceManager.GetString("SaveConfirm_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Redirector Config is changed. Press [Yes] to save. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveConfirm_Message {
            get {
                return ResourceManager.GetString("SaveConfirm_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Executable File (*.exe)|*.exe|All Files (*.*)|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SelectEditor_Filter {
            get {
                return ResourceManager.GetString("SelectEditor_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Script Editor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SelectEditor_Title {
            get {
                return ResourceManager.GetString("SelectEditor_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All Files (*.*)|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SelectTestFilename_Filter {
            get {
                return ResourceManager.GetString("SelectTestFilename_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select File To Open に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SelectTestFilename_Title {
            get {
                return ResourceManager.GetString("SelectTestFilename_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Solution File (*.sln)|*.sln|All Files (*.*)|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SelectTestSolution_Filter {
            get {
                return ResourceManager.GetString("SelectTestSolution_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Solution File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SelectTestSolution_Title {
            get {
                return ResourceManager.GetString("SelectTestSolution_Title", resourceCulture);
            }
        }
    }
}
